INSERT INTO RISKAREA(PUBLIC_DATE,PUBLIC_TIME,RISK_GRADE,LOCATION_NO,UPDATE_TIME)
 (select r.PUBLIC_DATE, r.PUBLIC_TIME, r.RISK_GRADE, l.LOCATION_NO, r.UPDATE_TIME
    from RISK_AREA r
    join LOCATIONS l
    on r.AREA_NAME = l.AREA_NAME and r.COMMUNITY = l.COMMUNITY and r.LOCATION = l.LOCATION)
order by PUBLIC_DATE;